import { expect, test } from './fixtures';

/**
 * Runs only against the built output (E2E_TARGET=dist), where the dev server's module loading
 * and proxy are gone. Kept to the shape of the build rather than repeating the app suite: the
 * bugs this target exists to catch are "it works in dev and not once built".
 */
test('the built public page renders without a request to the API', async ({ page }) => {
  const apiCalls: string[] = [];
  page.on('request', (r) => {
    if (r.url().includes('/api/')) apiCalls.push(r.url());
  });
  await page.goto('/');
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  // The marketing page imports nothing from lib/api, and this is what keeps that true: a
  // visitor who never signs in should cause no traffic to the app's API at all.
  expect(apiCalls, 'the public page should not call the API').toEqual([]);
});

test('the built portal boots and reaches the API', async ({ page }) => {
  const failed: string[] = [];
  page.on('response', (r) => {
    if (r.status() >= 400 && !r.url().includes('/api/me')) failed.push(`${r.status()} ${r.url()}`);
  });
  await page.goto('/app');
  // /api/me answering 401 for a signed-out visitor is correct, and is also proof the built
  // bundle is talking to the API rather than failing silently.
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible();
  expect(failed, 'unexpected failed requests').toEqual([]);
});

test('an unknown path renders the app but answers 404', async ({ page }) => {
  // Both halves matter and they pull in opposite directions. The app has to boot, or a deep
  // link that exists only client-side would show the host's own error page. The *status* still
  // has to be 404, because that is the only thing telling a crawler the page is not real —
  // and it is what GitHub Pages sends. Serving 200 here once hid a live console error.
  const res = await page.goto('/no-such-page');
  expect(res?.status()).toBe(404);
  await expect(page.getByRole('heading', { name: 'Nothing here' })).toBeVisible();
});

test('the icon is a real file, so nothing asks the origin root for one', async ({ page }) => {
  // With no <link rel="icon"> a browser asks the origin for /favicon.ico. Under a project
  // subpath that is not this site, so it 404s and the failure is logged to the console —
  // which Lighthouse counts against best-practices.
  const html = await (await page.request.get('/')).text();
  expect(html).toMatch(/<link rel="icon"[^>]*href="[^"]*favicon\.ico"/);

  const icon = await page.request.get('/favicon.ico');
  expect(icon.status()).toBe(200);
  expect(icon.headers()['content-type']).toContain('image');
});

test('the public pages carry their text without any JavaScript', async ({ browser, baseURL }) => {
  // What a crawler that does not run scripts sees, and what paints before the bundle arrives.
  // Prerendering is the only reason there is anything here at all: the app mounts into an
  // empty #root, so without it this page is a blank div.
  const context = await browser.newContext({ javaScriptEnabled: false, baseURL });
  const page = await context.newPage();

  await page.goto('/');
  await expect(page.locator('h1')).toContainText('multi-tenant app');
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');

  await page.goto('/ja');
  await expect(page.locator('h1')).toContainText('マルチテナント');
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja');

  await context.close();
});

test('the fallback stays the empty shell, not a copy of a prerendered page', async ({ page }) => {
  // 404.html is what the host serves for anything unmatched. A prerendered page copied here
  // would show that page's text at every unknown URL, which is worse than showing nothing.
  const res = await page.request.get('/404.html');
  const html = await res.text();

  // The root being *empty* is the thing, not the absence of a phrase. This used to look for
  // "multi-tenant app" anywhere in the file, which broke the moment the shell gained an
  // og:description — the words were present, in a meta tag, with the page still an empty shell.
  expect(html).toMatch(/<div id="root">\s*<\/div>/);
  expect(html, 'a prerendered page has a rendered heading in its body').not.toMatch(/<h1[^>]*>/);
});

test('the sitemap lists the public pages and nothing else', async ({ page }) => {
  const xml = await (await page.request.get('/sitemap.xml')).text();
  const urls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);

  expect(urls.length, `sitemap urls: ${urls.join(', ')}`).toBe(2);
  expect(urls.some((u) => u.endsWith('/ja'))).toBe(true);
  // The portal is behind a session and has nothing worth indexing.
  expect(urls.some((u) => u.includes('/app'))).toBe(false);
  // Generated by composing the origin with the build's base. Getting that wrong repeats the
  // base and every URL in the file is a 404.
  for (const url of urls) {
    const path = new URL(url).pathname;
    expect(path.match(/turbohamscaler/g)?.length ?? 0, `doubled base in ${url}`).toBeLessThan(2);
  }

  const robots = await (await page.request.get('/robots.txt')).text();
  expect(robots).toContain('Sitemap: ');
});
